system.updateStorage("main:point", 0)
system.updateStorage("main:mult", 1)
system.updateStorage("main:money", 50)
system.updateStorage("shop:maxCardAmount", 5)
system.updateStorage("main:maxCardAmount", 5)