name = "chartweaver"
default_targets = ["win64"]
build_directory = "D:/code/love2d/pricegamebuild"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
]

[win64]
love_binaries = "D:/code/love2d/love-12.0-win64"